language: python

python:
        - "3.5"

services: 
        - postgresql

env:
        -DJANGO=2.0 DB=postgresql

install: 
        - pip install -r requirements.txt


script: 
        - python manage.py test
